### ISSUE TITLE
Panic causes API to die

### ISSUE THREAD

**Issue by hashbender** [LuxorLabs/sia-blockchain-explorer#3]
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 2025553 [running]:
bufio.(*Writer).WriteString(0x0, 0xc4202b1620, 0x11, 0x11, 0xf33100, 0xf15220)
        /usr/lib/go-1.8/src/bufio/bufio.go:664 +0x41
net/http.(*chunkWriter).writeHeader(0xc42e095c38, 0xc428ef2000, 0x54792, 0x5d8f3)
        /usr/lib/go-1.8/src/net/http/server.go:1382 +0x91d
net/http.(*chunkWriter).Write(0xc42e095c38, 0xc428ef2000, 0x54792, 0x5d8f3, 0x0, 0xc42e095c40, 0xc42013cc70)
        /usr/lib/go-1.8/src/net/http/server.go:347 +0x32a
bufio.(*Writer).Write(0xc42add03c0, 0xc428ef2000, 0x54792, 0x5d8f3, 0x0, 0xb21960, 0xc42cc75540)
        /usr/lib/go-1.8/src/bufio/bufio.go:598 +0x15f
net/http.(*response).write(0xc42e095c00, 0x54792, 0xc428ef2000, 0x54792, 0x5d8f3, 0x0, 0x0, 0xc420a8f600, 0x1, 0x54791)
        /usr/lib/go-1.8/src/net/http/server.go:1525 +0x150
net/http.(*response).Write(0xc42e095c00, 0xc428ef2000, 0x54792, 0x5d8f3, 0x0, 0x0, 0xc4220e8088)
        /usr/lib/go-1.8/src/net/http/server.go:1495 +0x64
encoding/json.(*Encoder).Encode(0xc42cc75670, 0xa4e680, 0xc422ac4ae0, 0xe04fa0, 0xc42e095c00)
        /usr/lib/go-1.8/src/encoding/json/stream.go:218 +0x1ef
github.com/NebulousLabs/Sia/api.WriteJSON(0xe0b120, 0xc42e095c00, 0xa4e680, 0xc422ac4ae0)
        /home/luxor/Go/src/github.com/NebulousLabs/Sia/api/api.go:356 +0x10e
github.com/NebulousLabs/Sia/api.(*API).explorerHandler(0xc4200d0180, 0xe0b120, 0xc42e095c00, 0xc431081000, 0x0, 0x0, 0x0)
        /home/luxor/Go/src/github.com/NebulousLabs/Sia/api/explorer.go:505 +0x22c
github.com/NebulousLabs/Sia/api.RequireUserAgent.func1(0xe0b120, 0xc42e095c00, 0xc431081000)
        /home/luxor/Go/src/github.com/NebulousLabs/Sia/api/api.go:100 +0xba
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.1(0xc4257a1620, 0xe06360, 0xc

**Comment by hashbender** [comment]
Happened again

`2018/01/01 11:37:57 http: multiple response.WriteHeader calls                                                                                                                              │··········································································
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                    │··········································································
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x503778]                                                                                                                    │··········································································
                                                                                                                                                                                           │··········································································
goroutine 2357359 [running]:                                                                                                                                                               │··········································································
bufio.(*Writer).Flush(0xc426098180, 0xc439fbe532, 0xffb)                                                                                                                                   │··········································································
        /usr/lib/go-1.8/src/bufio/bufio.go:566 +0x58                                                                                                                                       │··········································································
bufio.(*Writer).Write(0xc426098180, 0xc439fbe532, 0x60734, 0xdd24f, 0xc42e611450, 0x1, 0x1)                                                                                                │··········································································
        /usr/lib/go-1.8/src/bufio/bufio.go:602 +0xdf                                                                                                                                       │··········································································
net/http.(*chunkWriter).Write(0xc42a0e22d8, 0xc439f02000, 0x11cc66, 0x199781, 0x0, 0xc42a0e22e0, 0xc4200cea90)                                                                             │··········································································
        /usr/lib/go-1.8/src/net/http/server.go:360 +0xc4                                                                                                                                   │··········································································
bufio.(*Writer).Write(0xc42379b500, 0xc439f02000, 0x11cc66, 0x199781, 0x0, 0xb21960, 0xc42e611540)                                                                                         │··········································································
        /usr/lib/go-1.8/src/bufio/bufio.go:598 +0x15f                                                                                                                                      │··········································································
net/http.(*response).write(0xc42a0e22a0, 0x11cc66, 0xc439f02000, 0x11cc66, 0x199781, 0x0, 0x0, 0xc42318e8f0, 0x1, 0x11cc65)                                                                │··········································································
        /usr/lib/go-1.8/src/net/http/server.go:1525 +0x150                                                                                                                                 │··········································································
net/http.(*response).Write(0xc42a0e22a0, 0xc439f02000, 0x11cc66, 0x199781, 0x0, 0x0, 0xc42faa73c8)                                                                                         │··········································································
        /usr/lib/go-1.8/src/net/http/server.go:1495 +0x64                                                                                                                                  │··········································································
encoding/json.(*Encoder).Encode(0xc42e611670, 0xa4e680, 0xc4282dc700, 0xe04fa0, 0xc42a0e22a0)                                                                                              │··········································································
        /usr/lib/go-1.8/src/encoding/json/stream.go:218 +0x1ef                                                                                                                             │··········································································
github.com/NebulousLabs/Sia/api.WriteJSON(0xe0b120, 0xc42a0e22a0, 0xa4e680, 0xc4282dc700)                                                                                                  │··········································································
        /home/luxor/Go/src/github.com/NebulousLabs/Sia/api/api.go:356 +0x10e                                                                                                               │··········································································
github.com/NebulousLabs/Sia/api.(*API).explorerHandler(0xc4200d0240, 0xe0b120, 0xc42a0e22a0, 0xc430628d00, 0x0, 0x0, 0x0)                                                                  │··········································································
        /home/luxor/Go/src/github.com/NebulousLabs/Sia/api/explorer.go:505 +0x22c                                                                                                          │··········································································
github.com/NebulousLabs/Sia/api.(*API).(github.com/NebulousLabs/Sia/api.explorerHandler)-fm(0xe0b120, 0xc42a0e22a0, 0xc430628d00, 0x0, 0x0, 0x0)                                           │··········································································
        /home/luxor/Go/src/github.com/NebulousLabs/Sia/api/api.go:226 +0x66                                                                                                                │··········································································
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc420244c40, 0xe0b120, 0xc42a0e22a0, 0xc430628d00)                                                                                │··········································································
        /home/luxor/Go/src/github.com/julienschmidt/httprouter/router.go:344 +0x813                                                                                                        │··········································································
github.com/NebulousLabs/Sia/api.RequireUserAgent.func1(0xe0b120, 0xc42a0e22a0, 0xc430628d00)                                                                                               │··········································································
        /home/luxor/Go/src/github.com/NebulousLabs/Sia/api/api.go:100 +0xba                                                                                                                │··········································································
net/http.HandlerFunc.ServeHTTP(0xc420248120, 0xe0b120, 0xc42a0e22a0, 0xc430628d00)                                                                                                         │··········································································
        /usr/lib/go-1.8/src/net/http/server.go:1942 +0x44                                                                                                                                  │··········································································
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.1(0xc420a71c80, 0xe06360, 0xc420248120, 0xe0b120, 0xc42a0e22a0, 0xc430628d00)                                                      │··········································································
        /home/luxor/Go/src/github.com/NebulousLabs/Sia/api/api.go:133 +0x79                                                                                                                │··········································································
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1                                                                                                                         │··········································································
        /home/luxor/Go/src/github.com/NebulousLabs/Sia/api/api.go:134 +0xbc   `

**Comment by hashbender** [comment]
This should be fixed, but will monitor
